<?php

namespace Mns\Service\AbcdataHub;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-05-04 at 17:19:51.
 */
class OrderResponseLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var OrderResponseLine
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OrderResponseLine(
            testHelper::helperArrayItems(),
            testHelper::heleperOrderGetResult()
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Mns\Service\AbcdataHub::__construct
     */
    public function test__construct()
    {
        $this->assertEquals(
            0.01
            , $this->object->Price->PriceValue
        );

    }

}
